name: Flutter Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FLUTTER_VERSION: 3.22.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/flutter
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}

      - name: Install Flutter
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        run: |
          curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
          tar -xf ./flutter_linux_${FLUTTER_VERSION}-stable.tar.xz -C ${GITHUB_WORKSPACE}
          export PATH="${GITHUB_WORKSPACE}/flutter/bin:$PATH"
          flutter config --no-analytics
          flutter config --no-cli-animations
          flutter doctor
      
      - name: Add Flutter to Path
        run: echo "${GITHUB_WORKSPACE}/flutter/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build Web
        run: flutter build web --release

      - uses: actions/upload-pages-artifact@v3
        name: Upload Artifact
        with:
          name: github-pages
          path: build/web/
  
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  