name: Flutter Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FLUTTER_VERSION: 3.22.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        run: |
          curl https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_$FLUTTER_VERSION-stable.tar.xz
          tar -xf ./flutter_linux_$FLUTTER_VERSION-stable.tar.xz -C /usr/bin
          export PATH="/usr/bin/flutter/bin:$PATH"
          flutter doctor
          echo 'export PATH="/usr/bin/flutter/bin:$PATH"' >> $GITHUB_ENV

